import React from 'react';
import {shallow} from 'enzyme';
import {DropdownButton, MenuItem} from "react-bootstrap";

import DropdownList from '../DropdownList';

describe('DropdownList component should', () =>{
  const items = [{name: 'January', value: "0"}, {name: 'February', value: "1"}, {name: 'March', value: "2"}];

  describe('render the top level components with:', () => {
    const dropdownList = shallow(<DropdownList items={items} />);

    test('a DropdownButton component', () => {
      expect(dropdownList.find(DropdownButton).exists()).toEqual(true);
    });
    test("a default title as 'Select...'", () => {
      expect(dropdownList.find(DropdownButton).prop('title')).toEqual('Select...');
    });
    test('an id for the DropdownButton generated by default', () => {
      expect(dropdownList.find(DropdownButton).prop('id')).toBeTruthy();
    });
  });

  test('render the supplied items correctly', () => {
    const dropDownList = shallow(<DropdownList id="ddl" items={items}/>);
    const menuItems = dropDownList.find(MenuItem);

    expect(menuItems.length).toEqual(items.length);
    items.forEach((item, i) => {
      expect(menuItems.at(i).prop('eventKey')).toEqual(item.value);
      expect(menuItems.at(i).childAt(0).text()).toEqual(item.name);
      expect(menuItems.at(i).prop('onSelect')).toBeDefined();
    });
  });

  test("render the selected item's name as title of DropdownButton", () => {
    const dropdownList = shallow(<DropdownList id="ddl" items={items} selectedItem="1"/>);
    expect(dropdownList.find(DropdownButton).prop('title')).toEqual('February');
  });

  test('onItemSelected handler is invoked with correct arguments', () => {
    const onItemSelected = jest.fn();
    const dropDownList = shallow(<DropdownList id="ddl" items={items} onItemSelected={onItemSelected} />);
    dropDownList.find(MenuItem).at(1).prop('onSelect')('1');

    expect(onItemSelected).toHaveBeenCalledWith('1');
  });

  test('onItemSelected handler is NOT invoked when no handler is supplied', () => {
    const onItemSelected = jest.fn();
    const dropdownList = shallow(<DropdownList id="ddl" items={items}/>);
    dropdownList.find(MenuItem).at(1).prop('onSelect')('1');
    expect(onItemSelected).not.toHaveBeenCalled();
  });
});
